# Generated by Django 2.1.7 on 2022-01-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220117_0957'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='api_user',
        ),
    ]
