# Generated by Django 2.1.7 on 2022-01-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220117_1106'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='api_user',
        ),
    ]
