# Generated by Django 2.1.3 on 2020-01-17 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_search_result', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSearchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_search_item_id', models.IntegerField(blank=True, default=0, verbose_name='id')),
                ('title', models.TextField(blank=True, verbose_name='title')),
                ('html_title', models.TextField(blank=True, verbose_name='html_title')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('display_link', models.CharField(blank=True, max_length=255, verbose_name='display_link')),
                ('snippet', models.TextField(blank=True, default=0, verbose_name='snippet')),
                ('html_snippet', models.TextField(blank=True, verbose_name='html_snippet')),
                ('formatted_url', models.URLField(blank=True, verbose_name='formatted_url')),
                ('html_formatted_url', models.URLField(blank=True, verbose_name='html_formatted_url')),
                ('google_search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_search_result.GoogleSearchResult')),
            ],
        ),
    ]
