# Generated by Django 2.1.3 on 2020-01-17 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.IntegerField(blank=True, default=0, verbose_name='friend_id')),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_user.TwitterUser')),
            ],
        ),
    ]
