# Generated by Django 2.1.3 on 2020-01-17 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_search_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSearchItemPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_search_item_page_id', models.IntegerField(blank=True, default=0, verbose_name='id')),
                ('html', models.TextField(blank=True, verbose_name='html')),
                ('google_search_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_search_item.GoogleSearchItem')),
            ],
        ),
    ]
