# Generated by Django 2.1.3 on 2020-01-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_id', models.IntegerField(blank=True, default=0, verbose_name='id')),
                ('search_engin_id', models.CharField(blank=True, max_length=255, verbose_name='engin_id')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='domain')),
                ('terms_url', models.CharField(blank=True, max_length=255, verbose_name='terms_url')),
            ],
        ),
    ]
