# Generated by Django 2.1.3 on 2020-01-17 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('tweet_id', models.BigIntegerField(blank=True, default=0, verbose_name='id')),
                ('id_str', models.TextField(blank=True, verbose_name='id_str')),
                ('snippet', models.TextField(blank=True, verbose_name='snippet')),
                ('source', models.TextField(blank=True, verbose_name='source')),
                ('truncated', models.BooleanField(verbose_name='truncated')),
                ('in_reply_to_status_id', models.BigIntegerField(blank=True, default=0, verbose_name='in_reply_to_status_id')),
                ('in_reply_to_status_id_str', models.TextField(blank=True, verbose_name='in_reply_to_status_id_str')),
                ('in_reply_to_user_id', models.BigIntegerField(blank=True, default=0, verbose_name='in_reply_to_user_id')),
                ('in_reply_to_user_id_str', models.TextField(blank=True, verbose_name='in_reply_to_user_id_str')),
                ('in_reply_to_screen_name', models.TextField(blank=True, verbose_name='in_reply_to_screen_name')),
                ('quoted_status_id', models.BigIntegerField(blank=True, default=0, verbose_name='quoted_status_id')),
                ('quoted_status_id_str', models.TextField(blank=True, verbose_name='quoted_status_id_str')),
                ('is_quote_status', models.BooleanField(verbose_name='is_quoted_status')),
                ('quoted_status', models.TextField(blank=True, verbose_name='quoted_status')),
                ('retweeted_status', models.TextField(blank=True, verbose_name='retweeted_status')),
                ('quote_count', models.IntegerField(blank=True, default=0, verbose_name='quoted_count')),
                ('reply_count', models.IntegerField(blank=True, default=0, verbose_name='reply_count')),
                ('retweet_count', models.IntegerField(blank=True, default=0, verbose_name='retweet_count')),
                ('favorite_count', models.IntegerField(blank=True, default=0, verbose_name='favorite_count')),
                ('favorited', models.BooleanField(verbose_name='favorited')),
                ('retweeted', models.BooleanField(verbose_name='retweeted')),
                ('possibly_sensitive', models.BooleanField(verbose_name='possibly_sensitive')),
                ('lang', models.TextField(blank=True, verbose_name='lang')),
                ('tag', models.TextField(blank=True, verbose_name='tag')),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_user.TwitterUser')),
            ],
        ),
    ]
